"""LLM provider abstraction: OpenAI / Anthropic / Gemini / Mock.

Each provider implements `generate_design_json(system, user) -> dict`.
The mock provider produces a deterministic, schema-valid design from the
user parameters so the full pipeline works with no API keys.
"""

import json
import logging

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)


async def _openai_generate(system: str, user: str) -> dict:
    async with httpx.AsyncClient(timeout=60) as client:
        resp = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {settings.OPENAI_API_KEY}"},
            json={
                "model": "gpt-4o-mini",
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "response_format": {"type": "json_object"},
                "temperature": 0.2,
            },
        )
        resp.raise_for_status()
        return json.loads(resp.json()["choices"][0]["message"]["content"])


async def _anthropic_generate(system: str, user: str) -> dict:
    async with httpx.AsyncClient(timeout=60) as client:
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={"x-api-key": settings.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01"},
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 4096,
                "system": system,
                "messages": [{"role": "user", "content": user + "\nReturn only JSON, no prose."}],
            },
        )
        resp.raise_for_status()
        text = resp.json()["content"][0]["text"]
        start, end = text.find("{"), text.rfind("}") + 1
        return json.loads(text[start:end])


def _mock_generate(project_type: str, params: dict) -> dict:
    """Deterministic schema-valid design used when no AI keys are configured."""
    base = {
        "project_type": project_type,
        "assumptions": [
            "No verified geotechnical borehole data provided",
            "Traffic/usage load is preliminary",
            "Utility data unavailable",
            "Generated by mock AI provider (no API key configured)",
        ],
        "risks": ["soil bearing capacity unknown", "existing utilities unknown"],
        "required_engineer_review": True,
        "required_permissions": [],
    }
    if project_type == "flyover":
        length = float(params.get("length_m", 500))
        spacing = float(params.get("pier_spacing_m", 30))
        return {
            **base,
            "summary": f"Preliminary {params.get('lanes', 4)}-lane flyover concept, {length:.0f}m long",
            "geometry": {
                "length_m": length,
                "deck_width_m": float(params.get("deck_width_m", 16)),
                "clearance_m": float(params.get("clearance_m", 5.5)),
                "pier_spacing_m": spacing,
                "pier_count": max(2, int(length / spacing) + 1),
                "foundation_depth_m_assumed": float(params.get("foundation_depth_m_assumed", 8)),
            },
            "materials": {
                "concrete_grade": params.get("concrete_grade", "M35") + " assumed",
                "steel_grade": params.get("steel_grade", "Fe500") + " assumed",
                "asphalt_thickness_mm": params.get("asphalt_thickness_mm", 80),
            },
            "layers": [
                {"name": "foundation", "description": "Assumed pile/open foundation placeholder"},
                {"name": "piers", "description": "Vertical supports"},
                {"name": "pier_caps", "description": "Cap beams"},
                {"name": "deck_slab", "description": "Main slab"},
                {"name": "road_surface", "description": "Wearing coat/asphalt"},
                {"name": "barriers", "description": "Crash barriers/parapet"},
            ],
            "construction_sequence": [
                "survey and utility detection", "traffic diversion planning",
                "foundation construction", "pier construction", "girder placement",
                "deck slab casting", "road surfacing",
                "safety barriers and drainage", "testing and handover",
            ],
        }
    if project_type == "building":
        floors = int(params.get("floors", 4))
        return {
            **base,
            "summary": f"Preliminary G+{floors - 1} building massing concept",
            "geometry": {
                "builtup_area_sqm": float(params.get("builtup_area_sqm", 400)),
                "floors": floors,
                "floor_height_m": float(params.get("floor_height_m", 3.2)),
            },
            "materials": {
                "concrete_grade": params.get("concrete_grade", "M25") + " assumed",
                "steel_grade": params.get("steel_grade", "Fe500") + " assumed",
            },
            "layers": [
                {"name": "foundation", "description": "Foundation placeholder"},
                {"name": "columns", "description": "Column grid placeholder"},
                {"name": "slabs", "description": "Floor slabs"},
                {"name": "core", "description": "Stair/lift core placeholder"},
                {"name": "facade", "description": "Facade placeholder"},
            ],
            "construction_sequence": [
                "site survey and soil test", "excavation and foundation",
                "structural frame floor by floor", "masonry and services",
                "finishes", "testing and handover",
            ],
        }
    if project_type == "pipeline":
        return {
            **base,
            "summary": f"Preliminary {params.get('pipe_diameter_mm', 600)}mm pipeline/drainage concept",
            "geometry": {
                "length_m": float(params.get("length_m", 300)),
                "pipe_diameter_mm": float(params.get("pipe_diameter_mm", 600)),
            },
            "materials": {"pipe_material": params.get("pipe_material", "RCC") + " assumed"},
            "layers": [
                {"name": "trench", "description": "Excavated trench"},
                {"name": "bedding", "description": "Sand bedding"},
                {"name": "pipe", "description": "Pipe along alignment"},
                {"name": "backfill", "description": "Compacted backfill"},
                {"name": "manholes", "description": "Inspection chambers"},
            ],
            "construction_sequence": [
                "alignment survey and utility detection", "trench excavation",
                "bedding placement", "pipe laying and jointing",
                "manhole construction", "backfilling and compaction",
                "testing and road restoration",
            ],
        }
    # road
    return {
        **base,
        "summary": f"Preliminary {params.get('lanes', 2)}-lane road segment concept",
        "geometry": {
            "length_m": float(params.get("length_m", 1000)),
            "road_width_m": float(params.get("road_width_m", 7.5)),
        },
        "materials": {"asphalt_thickness_mm": params.get("asphalt_thickness_mm", 80)},
        "layers": [
            {"name": "formation", "description": "Prepared subgrade"},
            {"name": "base_course", "description": "Granular base/WMM"},
            {"name": "pavement", "description": "Bituminous surfacing"},
            {"name": "shoulders", "description": "Side shoulders"},
            {"name": "drains", "description": "Side drainage"},
        ],
        "construction_sequence": [
            "survey and setting out", "formation preparation",
            "base course laying", "asphalt paving",
            "markings and signage", "drainage works and handover",
        ],
    }


async def generate_design_json(system: str, user: str, project_type: str, params: dict) -> tuple[dict, str]:
    """Returns (design_json, provider_name). Falls back to mock on any failure."""
    if settings.OPENAI_API_KEY:
        try:
            return await _openai_generate(system, user), "openai"
        except Exception:
            logger.warning("OpenAI generation failed, trying next provider")
    if settings.ANTHROPIC_API_KEY:
        try:
            return await _anthropic_generate(system, user), "anthropic"
        except Exception:
            logger.warning("Anthropic generation failed, falling back to mock")
    return _mock_generate(project_type, params), "mock"
